<?php

require_once(dirname(__FILE__) . '/../config.php');
require_once($CFG->libdir . '/adminlib.php');

$strheading = 'Element Library: Notifications';
$url = new moodle_url('/elementlibrary/notifications.php');

// Start setting up the page
$params = array();
$PAGE->set_context(context_system::instance());
$PAGE->set_url($url);
$PAGE->set_title($strheading);
$PAGE->set_heading($strheading);

admin_externalpage_setup('elementlibrary');

echo $OUTPUT->header();

echo html_writer::link(new moodle_url('/elementlibrary/'), '&laquo; Back to index');
echo $OUTPUT->heading($strheading);


echo $OUTPUT->notification('This is an error notification <a href="#">with a link</a>');

echo $OUTPUT->notification('This is a success notification <a href="#">with a link</a>', 'notifysuccess');

echo $OUTPUT->notification('This is a standard notification <a href="#">with a link</a>', 'notifymessage');

echo $OUTPUT->notification('This is a "notice" notification. <a href="#">with a link</a> At the moment we\'ve got a class "notifynotice" and the moodle class "notice" styled like this. We may want to remove the styles from "notice" or get rid of "notifynotice" and just use "notice" depending on how much "notice" is used and if it\'s appropriate.', 'notifynotice');

echo $OUTPUT->notification('This is a redirect message notification. It looks like it\'s supposed to be used on a blank page as it has 10% top margin', 'redirectmessage');

echo $OUTPUT->error_text('This is an error generated using error_text(). I think this is used in form validation errors.');

echo $OUTPUT->box('This is a notice box <a href="#">with a link</a>, generated via box() with "generalbox" and "notice" classes added. Used by moodle in various places.', array('generalbox', 'notice'));

echo $OUTPUT->confirm('This is a confirmation box <a href="#">with a link</a>, generated by confirm(). It has the "box" and "generalbox" styles applied, as well as an id of "notice"', new moodle_url('notifications.php'), new moodle_url('notifications.php'));

echo $OUTPUT->container('In some cases you might want to prevent notifications from showing the border/background, in places where there is not enough room. You can do this with the .nobox class - any notifications inside a container with that class will not show the border/background. E.g.:');

echo $OUTPUT->container($OUTPUT->notification('This is a notification without the border/background', 'notifysuccess'), 'nobox');

echo $OUTPUT->footer();
